<?php
/**
 * Поле типа "Пароль".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>

<input
	type="password"
	name="<?= $field['input_name'] ?>"
	placeholder="<?= $field['title'] ?>"
	<?= (isset($field['required']) ? ' required ' : '') ?>
	value="<?= isset($field['value']) ? $field['value'] : '' ?>"
/>

<span class="sub_text"><?= $field['title'] ?></span>
