<?php
/**
 * Список категорий первого уровня в карте сайта.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var array $categoryList
 */

$data = $this->getMainCategories();
$categoryList = $data['items'];
?>

<div umi:add-method="none"
     umi:element-id="<?= $data['category_id'] ?>"
     umi:region="list"
     umi:module="catalog"
     umi:sortable="sortable"
>
	<?php foreach ($categoryList as $category): ?>
		<div umi:element-id="<?= $category['id'] ?>" umi:region="row">
			<a href="<?= $category['link'] ?>"
			   umi:field-name="name"
			   umi:delete="delete"
			   umi:empty="<?= $this->translate('empty_section_name') ?>"
			>
				<?= $category['text'] ?>
			</a>

			<?= $this->render($category, 'content/sitemap/category/sub_list') ?>
		</div>
	<?php endforeach; ?>
</div>

