<?php
/**
 * Меню основных страниц в шапке сайта (левое или правое).
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var string $variables
 * @var array $pageList
 */

$menuId = $variables;
$data = $this->getMenu($menuId);
$pageList = $data['lines'];
?>

<ul class="list_inline">
	<?php foreach ($pageList as $page): ?>
		<li>
			<a href="<?= $page['link'] ?>">
				<?= $page['name'] ?>
			</a>
		</li>
	<?php endforeach; ?>
</ul>
