<?php
/**
 * Блок с новостями и опросом на главной.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$lastVote = $this->getLastVote();
?>

<div class="container news_container mobile_all_width">
	<div class="row">
		<div class="col-md-6 main_news background_gray">
			<h3 class="block_capt up">
				<?= $this->translate('news') ?>
			</h3>

			<a href="/news1" class="blue_link hidden-xs hidden-sm">
				<?= $this->translate('all_news') ?>
			</a>

			<?= $this->render($variables, 'content/home/news/list') ?>
		</div>

		<?php if ($this->canShowVoteForm($lastVote)): ?>
			<?= $this->render($lastVote, 'content/home/vote/form') ?>
		<?php elseif ($this->canShowVoteResults($lastVote)): ?>
			<?= $this->render($lastVote, 'content/home/vote/results') ?>
		<?php else: ?>
			<div class="interview col-md-6">
				<h3 class="block_capt up">
					<?= $this->translate('vote_no_results') ?>
				</h3>
			</div>
		<?php endif; ?>
	</div>
</div>
