<?php
/**
 * Поле типа "Кнопка-флажок".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>
<!-- Первоначальный вариант в файле boolean0.phtml -->
<div>	
		<input
			onclick="show('upakovka')";
			type="checkbox"
			class="<? if ($field['name'] === "podarochnaya_upakovka") echo 'update_price buy_link_upak once'
			//  $basketCustom['summary']['price']['actual'] = $basketCustom['summary']['price']['actual'] + 500;?>"
			<? if ($field['name'] === "podarochnaya_upakovka") echo 'data-id="407363"' ?>
			id = "<?= $field['name'] ?>"
			name="<?= $field['input_name'] ?>"
			placeholder="<?= $field['title'] ?>"
			<?= (isset($field['required']) ? ' required ' : '') ?>
			value="<?= isset($field['value']) ? $field['value'] : '' ?>"
		/>
	<label 
		for="<?= $field['name']?>" 
	>
		<p><?= $field['title'] ?></p>
	</label>
</div>
