<?php
/**
 * Поле типа "Строка".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>
<? $required = isset($field['required']) ? 'required' : '' ?>

<? if($field['name'] == 'phone'): ?>
    <input
            type="tel"
            name="<?= $field['input_name'] ?>"
            value="<?= isset($field['value']) ? $field['value'] : '' ?>"
            placeholder="+7 (___) ___-__-__"
            class="input <?= $required ?>"
    />
<? else: ?>
    <input
            type="text"
            name="<?= $field['input_name'] ?>"

            value="<?= isset($field['value']) ? $field['value'] : '' ?>"
            class="input"
    />
<? endif; ?>



