<?php
/**
 * Поле типа "Строка".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>
<? $required1 = isset($field['required']) ? 'required' : '' ?>
<!-- 
    Убрал ниже шаблон телефона, идет перед классом    
placeholder="+7 (___) ___-__-__" -->
<? if($field['name'] == 'phone'): ?>
    <input
            type="tel"
            name="<?= $field['input_name'] ?>"
            value="<?= isset($field['value']) ? $field['value'] : '' ?>"
            
            class="input"
    />
<? else: ?>
<!-- Ниже в class убрал  $required  07.02.19 -->
    <input
            type="text"
            name="<?= $field['input_name'] ?>"

            value="<?= isset($field['value']) ? $field['value'] : '' ?>"
            
            class="input"
    />
<? endif; ?>



