<?php
/**
 * Список последних новостей на главной.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var array $newsItemList
 */

$lastNews = $this->macros('news','lastlistCustom',[$variables['page']->id]);
$newsItemList = $lastNews['items'];
$pagination = $this->getPagination($lastNews);
?>

<?php if (count($newsItemList) > 0): ?>
	<section class="articles inline">
			<div class="grid">

					<? foreach($lastNews['items'] as $item): ?>
							<?= $item['html'] ?>
					<? endforeach; ?>

			</div>

	</section>
    <?= $this->render($pagination, 'library/pagination') ?>

<?php endif; ?>
