<?php
/**
 * Превью категории.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var iUmiHierarchyElement $variables
 */

 
$category = $variables;
$name = $this->escape($category->getName());





?>

<form class="category_filtr">




 <section class="content right">

    <section class="products">
      <div class="grid">
<a href="<?= $this->getPath($category) ?>" class="subsection_item">



   	<div class="thumb">
		<?= $this->render(
			[
				'id' => $category->getId(),
				'field_name' => 'photo',
				'src' => $this->getPhotoPath($category),
				'alt' => '',
				'title' => '',
				'width' => 200,
				'height' => 150,
			],
			'library/thumbnail'
		) ?>
	</div>

	<div class="text"
	     umi:element-id="<?=$category->getId()?>"
	     umi:field-name="name"
	     umi:empty="<?= $this->translate('empty') ?>"
	     umi:delete="delete"
	>
		<?= $name ?>
	</div>
</a>


</div>

</section>



    </section>


</form>

<div class="clear"></div>
