<?php
/**
 * Поле типа "Строка".
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$field = $variables;
?>
<? $required = (isset($field['required']) ? 'required' : '') ?>
<? $class = isset($field['class']) ? $field['class'] : '' ?>
<div class="line <?= $class ?>">
	<div class="name"><?= $field['title'] ?><?= (isset($field['required']) ? ' * ' : '') ?></div>
	<div class="field">
		<?= $this->render($field, "data/form_field/{$field['type']}") ?>
	</div>
</div>
