<?php
/**
 * Контент новости.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 * @var iUmiHierarchyElement $newsItem
 * @var string|null $photoPath
 */

$newsItem = $variables['page'];
$photoPath = $this->getNewsItemPhotoPath($newsItem);
?>

<div class="free_text" umi:element-id="<?= $variables['pageId'] ?>" umi:field-name="content"
	 umi:empty="<?= $this->translate('empty_page_content') ?>">
	<?= $newsItem->getValue('content') ?>
</div>
