<?php
/**
 * Блок с копирайтом на десктопной версии.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
$settingsContainer = $this->getSettingsContainer();
?>

<div class="copyright align_left">
	<p class="up"  umi:object-id="<?= $settingsContainer->getId() ?>" umi:field-name="copyright">
		<?= $settingsContainer->getValue('copyright') ?> <?= $this->getCurrentYear() ?>
	</p>

	<div class="footer_payment" umi:object-id="<?= $settingsContainer->getId() ?>" umi:field-name="after_copyright_text">
		<?= $settingsContainer->getValue('after_copyright_text') ?>
	</div>
</div>
