<?php
/**
 * Мобильная версия подвала сайта:
 *   - Форма подписки на новости
 *   - Социальные кнопки
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$settingsContainer = $this->getSettingsContainer();
?>

<div class="container mobile_footer visible-xs visible-sm">
	<div class="row">
		<h4 class="gray_text footer_capt"
		    umi:object-id="<?= $settingsContainer->getId() ?>" umi:field-name="dispatches_text">
			<?= $settingsContainer->getValue('dispatches_text') ?>
		</h4>

		<?= $this->render($this->macros('dispatches', 'subscribe', [null, $variables['user']['id']]), 'layout/footer/subscribe') ?>
	</div>

	<div class="row bottom_footer">
		<div class="col-xs-6">
			<p umi:object-id="<?= $settingsContainer->getId() ?>" umi:field-name="copyright">
				<?= $settingsContainer->getValue('copyright') ?> <?= $this->getCurrentYear() ?>
			</p>
		</div>

		<div class="col-xs-6">
			<ul class="mobile_social list_inline">
				<?= $this->render($variables, 'layout/footer/social') ?>
			</ul>
		</div>
	</div>
</div>
