<?php
/**
 * Опция поля умных фильтров, которое нужно вывести с чекбоксом.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$data = $this->getCheckboxFilterFieldData($variables);

$checked = $data['is-selected'] ? "checked" : "";
?>

<div class="line">
<!-- Вставил условие на исключение варианта где "S, M, L" 21.02.19 -->
	<? if ($data['value'] != "S, M, L") : ?>
	<input type="checkbox" name="<?= $data['name'] ?>" id="field_<?= $data['id'] ?>" value="<?= $data['value'] ?>" <?= $checked  ?>>
	<label for="field_<?= $data['id'] ?>"><?= $data['value'] ?></label>
	<? endif; ?>
</div>
