<?php
/**
 * Список способов доставки.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$deliveryList = $variables;
file_put_contents("umitest", var_export($deliveryList, true)."\n", FILE_APPEND | LOCK_EX);
?>

<?php foreach ($deliveryList as $delivery): ?>
	<?php if ($this->isApiShipDelivery($delivery)): ?>
		<?= $this->render($delivery, 'emarket/delivery/choose/apiship') ?>
	<?php else: ?>
		<?= $this->render($delivery, 'emarket/delivery/choose/item') ?>
	<?php endif; ?>
<?php endforeach; ?>
