<?php
/**
 * Системная страница `emarket/gateway`. Обычно при запросе этого макроса шаблон не отображается,
 * но если мы сюда зашли - выводим сообщение об ошибке.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
?>

<?php if (isset($variables['data'])): ?>
	<div class="container">
		<div class="error">
			<h3><?= $this->translate('errors') ?></h3>
			<p><?= $variables['data'] ?></p>
		</div>
	</div>
<?php endif; ?>
