<?php
/**
 * Блок покупки товара:
 *   - Цена
 *   - Наличие
 *   - Кнопки "Купить" и "Купить в один клик"
 *   - Отзывы в мобильной версии
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */

$product = $variables;
?>

<div class="row top_row">
	<div class="col-md-6 col-xs-12">
		<div class="top_block">
			<h2>
				<sup>
					<?= $this->render($product, 'emarket/old_price') ?>
				</sup>

				<span umi:element-id="<?= $product->getId() ?>" umi:field-name="price">
					<?= $this->getPrice($product) ?>
				</span>
			</h2>
		</div>

		<a href="<?= $this->getAddToCartLink($product) ?>"
		   class="transparent_btn item_btn hidden-xs hidden-sm add_to_cart_button <?= $this->getBuyButtonClass($product) ?>">
			<?= $this->translate('purchase') ?>
		</a>
	</div>

	<div class="col-md-6 col-xs-12">
		<div class="top_block clearfix">
			<?= $this->render($product, 'catalog/product/main/price/stock_status') ?>
			<?= $this->render($product, 'catalog/product/main/price/mobile_ratings') ?>
		</div>

		<a href="<?= $this->getAddToCartLink($product) ?>"
		   class="transparent_btn item_btn visible-xs visible-sm add_to_cart_button <?= $this->getBuyButtonClass($product) ?>">
			<?= $this->translate('purchase') ?>
		</a>

		<a class="buy_one_click_button transparent_btn item_one_click <?= $this->getBuyButtonClass($product) ?>">
			<?= $this->translate('purchase_one_click') ?>
		</a>
	</div>
</div>
