<?php
/**
 * Логотип сайта.
 *
 * @var umiTemplaterPHP|ViewPhpExtension|DemomarketPhpExtension $this
 * @var array $variables
 */
$settingsContainer = $this->getSettingsContainer();
?>

<div class="col-md-3 header_logo">
	<div class="media">
		<a href="<?= $this->getHomePageUrl() ?>">
			<div class="media-left">
				<img
					umi:object-id="<?= $settingsContainer->getId() ?>" umi:field-name="logo"
					src="<?= $settingsContainer->getValue('logo') ?>"
					alt="<?= $settingsContainer->getValue('site_name') ?>"
				>
			</div>
			<div class="media-body">
				<h2 class="media-heading up" umi:object-id="<?= $settingsContainer->getId() ?>"
				    umi:field-name="site_name">
					<?= $settingsContainer->getValue('site_name') ?>
				</h2>
				<span class="gray_text up" umi:object-id="<?= $settingsContainer->getId() ?>"
				      umi:field-name="header_under_name">
				<?= $settingsContainer->getValue('header_under_name') ?>
			</span>
			</div>
		</a>
	</div>
</div>
